In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
list_numbers = [1,2,3]

In [3]:
list_everything = [1, False, "Some random string"]

In [8]:
type(np.array([1,2,"1"]))

numpy.ndarray

In [9]:
classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

list

In [10]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [11]:
numpy_array.shape

(6,)

In [12]:
np.array([2,4]).mean()

3.0

In [13]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [14]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])

In [15]:
matrix1[0, :]

array([1, 2, 3])

In [16]:
matrix1[:, -1]

array([3, 6, 9])

In [17]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])

In [18]:
matrix2.sum()

47

In [19]:
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [20]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [21]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [22]:
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])

array([[ 9, 11],
       [13, 15]])

In [23]:
np.array([
	[1,2],
	[3,4]
]).dot([1,1])

array([3, 7])

In [24]:
v1 = np.arange(1, 11)

v2 = np.ones(10)

result = v1 + v2

print("Wektor 1:", v1)
print("Wektor 2:", v2)
print("Suma:", result)

Wektor 1: [ 1  2  3  4  5  6  7  8  9 10]
Wektor 2: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Suma: [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [25]:
matrix = np.arange(1, 26).reshape(5, 5)

print("Macierz:")
print(matrix)

row_means = matrix.mean(axis=1)

col_means = matrix.mean(axis=0)

print("Średnie wierszy:", row_means)
print("Średnie kolumn:", col_means)

Macierz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Średnie wierszy: [ 3.  8. 13. 18. 23.]
Średnie kolumn: [11. 12. 13. 14. 15.]
